const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const model = require(path.join(root, "models", "partnershipModel"));
const source = fs.readFileSync(path.join(root, "models", "partnershipModel.js"), "utf8");
const route = fs.readFileSync(path.join(root, "routes", "partnershipRoute.js"), "utf8");
const rebuild = fs.readFileSync(path.join(root, "database", "rebuild.sql"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "models", "accManagementDashboardModel.js"), "utf8");
for (const method of ["ensureSchema", "getDashboard", "createPartner", "updatePartnerStatus", "createIntegration", "issueCredential", "grantAccess", "authenticatePartnerKey", "recordExchange", "getPartnerProfile"]) assert.equal(typeof model[method], "function", `Missing partnership method: ${method}`);
for (let index = 1; index <= 10; index += 1) assert.ok(rebuild.includes(`ACC-FRS-PART-${String(index).padStart(3, "0")}`), `Missing partnership requirement ${index}`);
for (const table of ["partnership_partners", "partnership_integrations", "partnership_credentials", "partnership_access_grants", "partnership_verifications", "partnership_exchanges", "partnership_monitoring", "partnership_audit_logs"]) assert.ok(rebuild.includes(table), `Missing partnership table ${table}`);
for (const routePath of ["/admin/partnerships", "/admin/partnerships/partners", "/admin/partnerships/integrations", "/admin/partnerships/credentials", "/admin/partnerships/access", "/api/partners/v1/profile", "/api/partners/v1/exchanges"]) assert.ok(route.includes(routePath), `Missing partnership route ${routePath}`);
assert.ok(source.includes("partnership_exchanges") && source.includes("partnership_audit_logs") && source.includes("hashSecret") && source.includes("partner.profile.read"));
assert.ok(route.includes("admin.partnerships.manage") && route.includes("requirePartnerScope"));
assert.ok(dashboard.includes("partnershipModel.getDashboard") && dashboard.includes("activePartners"));
assert.ok(fs.existsSync(path.join(root, "views", "admin", "partnerships.ejs")));
assert.ok(fs.existsSync(path.join(root, "public", "styles", "partnerships.css")));
console.log("Chapter 44 third-party partnerships contract: PASS");
