const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const model = require(path.join(root, "models", "supportModel"));
const modelSource = fs.readFileSync(path.join(root, "models", "supportModel.js"), "utf8");
const route = fs.readFileSync(path.join(root, "routes", "supportRoute.js"), "utf8");
const controller = fs.readFileSync(path.join(root, "controllers", "supportController.js"), "utf8");
const rebuild = fs.readFileSync(path.join(root, "database", "rebuild.sql"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "models", "accManagementDashboardModel.js"), "utf8");
for (const method of ["ensureSchema", "createTicket", "listUserTickets", "getDashboard", "updateTicket", "createMaintenanceWindow"]) assert.equal(typeof model[method], "function", `${method} should be exported`);
for (const requirement of Array.from({ length: 10 }, (_, index) => `ACC-FRS-SUP-${String(index + 1).padStart(3, "0")}`)) assert.ok(rebuild.includes(requirement), `Missing support requirement: ${requirement}`);
for (const table of ["support_slas", "support_tickets", "support_ticket_comments", "support_ticket_attachments", "maintenance_windows", "maintenance_logs", "knowledge_base_articles", "support_improvements"]) assert.ok(rebuild.includes(table), `Missing support table: ${table}`);
for (const routePath of ["/support", "/support/report", "/support/tickets", "/admin/support", "/admin/support/tickets/:id", "/admin/support/maintenance"]) assert.ok(route.includes(routePath), `Missing support route: ${routePath}`);
assert.ok(route.includes("upload.single(\"screenshot\")"));
assert.ok(rebuild.includes("admin.support.read") && rebuild.includes("admin.support.manage"));
assert.ok(rebuild.includes("requirement_traceability") && rebuild.includes("chapter38-support.test.js"));
assert.ok(fs.existsSync(path.join(root, "views", "support", "help-center.ejs")));
assert.ok(fs.existsSync(path.join(root, "views", "support", "report-issue.ejs")));
assert.ok(fs.existsSync(path.join(root, "views", "admin", "support.ejs")));
assert.ok(fs.existsSync(path.join(root, "public", "styles", "support.css")));
assert.ok(controller.includes("createTicket") && controller.includes("scheduleMaintenance"));
assert.ok(modelSource.includes("notificationModel.generateNotification"));
assert.ok(dashboard.includes("supportModel.getDashboard"));
console.log("Chapter 38 maintenance and support contract: PASS");
