const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const model = require(path.join(root, "models", "releaseModel"));
const source = fs.readFileSync(path.join(root, "models", "releaseModel.js"), "utf8");
const route = fs.readFileSync(path.join(root, "routes", "releaseRoute.js"), "utf8");
const rebuild = fs.readFileSync(path.join(root, "database", "rebuild.sql"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "models", "accManagementDashboardModel.js"), "utf8");
for (const method of ["ensureSchema", "getDashboard", "createVersion", "createPlan", "recordNote", "recordCompatibility", "deploy", "rollback", "monitor", "toggleFeature"]) assert.equal(typeof model[method], "function", `Missing release method: ${method}`);
assert.equal(model.normalizeVersion("1.2.3"), "v1.2.3");
assert.equal(model.normalizeVersion("1.2"), null);
for (let index = 1; index <= 10; index += 1) assert.ok(rebuild.includes(`ACC-FRS-REL-${String(index).padStart(3, "0")}`), `Missing release requirement ${index}`);
for (const table of ["release_versions", "release_plans", "release_notes", "release_compatibility", "release_monitoring", "release_audit_logs"]) assert.ok(rebuild.includes(table), `Missing release table ${table}`);
for (const routePath of ["/admin/releases", "/admin/releases/versions", "/admin/releases/plans", "/admin/releases/deploy", "/admin/releases/rollback", "/admin/releases/features/:key"]) assert.ok(route.includes(routePath), `Missing release route ${routePath}`);
assert.ok(source.includes("SemVer") && source.includes("release_deployed") && source.includes("release_rolled_back") && source.includes("system_feature_flags"));
assert.ok(source.includes("environment_id") && source.includes("deployment_releases"), "Release deployment must link to Chapter 30 deployment records.");
assert.ok(rebuild.includes("environment_id INTEGER REFERENCES deployment_environments"), "Release plans must reference deployment environments.");
assert.ok(route.includes("admin.release.read") && route.includes("admin.release.manage"));
assert.ok(dashboard.includes("releaseModel.getDashboard"));
assert.ok(fs.existsSync(path.join(root, "views", "admin", "releases.ejs")));
assert.ok(fs.existsSync(path.join(root, "public", "styles", "releases.css")));
console.log("Chapter 41 versioning and release contract: PASS");
