const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const model = require(path.join(root, "models", "onboardingModel"));
const source = fs.readFileSync(path.join(root, "models", "onboardingModel.js"), "utf8");
const route = fs.readFileSync(path.join(root, "routes", "onboardingRoute.js"), "utf8");
const rebuild = fs.readFileSync(path.join(root, "database", "rebuild.sql"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "models", "accManagementDashboardModel.js"), "utf8");
for (const method of ["ensureSchema", "getDashboard", "importFile", "importApi", "createApiSource", "createAssistance", "updateAssistance", "validateRow"]) assert.equal(typeof model[method], "function", `Missing onboarding method: ${method}`);
for (let index = 1; index <= 10; index += 1) assert.ok(rebuild.includes(`ACC-FRS-ONB-${String(index).padStart(3, "0")}`), `Missing onboarding requirement ${index}`);
for (const table of ["onboarding_profiles", "migration_jobs", "migration_rows", "migration_api_sources", "onboarding_assistance", "onboarding_migration_audit_logs"]) assert.ok(rebuild.includes(table), `Missing onboarding table ${table}`);
for (const routePath of ["/admin/onboarding", "/admin/onboarding/files", "/admin/onboarding/api-sources", "/admin/onboarding/assistance"]) assert.ok(route.includes(routePath), `Missing onboarding route ${routePath}`);
assert.ok(source.includes("xlsx") && source.includes("validation") && source.includes("migration_completed") && source.includes("business_accounts"));
assert.ok(route.includes("admin.onboarding.read") && route.includes("admin.onboarding.manage"));
assert.ok(dashboard.includes("onboardingModel.getDashboard"));
assert.ok(fs.existsSync(path.join(root, "views", "admin", "onboarding.ejs")));
assert.ok(fs.existsSync(path.join(root, "public", "styles", "onboarding.css")));
console.log("Chapter 42 data migration and onboarding contract: PASS");
