const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const model = require(path.join(root, "models", "roadmapModel"));
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const sql = read("database/rebuild.sql");
const routes = read("routes/roadmapRoute.js");
const dashboard = read("models/accManagementDashboardModel.js");
const controller = read("controllers/roadmapController.js");
const requiredTables = ["roadmap_phases", "roadmap_goals", "roadmap_features", "roadmap_innovations", "roadmap_technology_evaluations", "roadmap_feedback", "roadmap_scalability_plans", "roadmap_audit_logs"];
const requiredMethods = ["ensureSchema", "getRoadmap", "getAdminDashboard", "createFeature", "updateFeature", "createInnovation", "createEvaluation", "createGoal", "createScalabilityPlan", "submitFeedback", "updateFeedback"];
requiredMethods.forEach((name) => assert.strictEqual(typeof model[name], "function", `${name} must be exported`));
requiredTables.forEach((table) => assert(sql.includes(table), `${table} missing`));
for (let index = 1; index <= 10; index += 1) assert(sql.includes(`ACC-FRS-ROAD-${String(index).padStart(3, "0")}`), `ROAD requirement ${index} missing`);
assert(routes.includes('router.get("/roadmap"'));
assert(routes.includes('router.get("/admin/roadmap"'));
assert(routes.includes('requirePermission("admin.roadmap.manage")'));
assert(controller.includes("roadmapModel.submitFeedback"));
assert(dashboard.includes("roadmapModel.getAdminDashboard"));
assert(read("views/roadmap/index.ejs").includes("/roadmap/feedback"));
assert(read("views/admin/roadmap.ejs").includes("/admin/roadmap/features"));
assert(read("public/styles/roadmap.css").includes(".roadmap-page"));
assert(sql.includes("release_plan_id BIGINT REFERENCES release_plans"));
assert(sql.includes("roadmap_audit_logs"));
console.log("Chapter 45 roadmap contract checks passed.");
