const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const model = require(path.join(root, "models", "qaModel"));
const rebuild = fs.readFileSync(path.join(root, "database", "rebuild.sql"), "utf8");
const source = fs.readFileSync(path.join(root, "models", "qaModel.js"), "utf8");
const route = fs.readFileSync(path.join(root, "routes", "qaRoute.js"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "models", "accManagementDashboardModel.js"), "utf8");
for (const method of ["ensureSchema", "getDashboard", "createPlan", "createCase", "executeCase", "createBug", "updateBug", "generateReport"]) assert.equal(typeof model[method], "function", `Missing QA method: ${method}`);
for (let index = 1; index <= 10; index += 1) assert.ok(rebuild.includes(`ACC-FRS-QA-${String(index).padStart(3, "0")}`), `Missing QA requirement ${index}`);
for (const table of ["qa_test_plans", "qa_test_cases", "qa_test_runs", "qa_bugs", "qa_reports"]) assert.ok(rebuild.includes(table), `Missing QA table ${table}`);
for (const routePath of ["/admin/qa", "/admin/qa/plans", "/admin/qa/cases", "/admin/qa/runs", "/admin/qa/bugs", "/admin/qa/reports"]) assert.ok(route.includes(routePath), `Missing QA route ${routePath}`);
assert.ok(source.includes("automated") && source.includes("manual") && source.includes("regression") && source.includes("release_readiness"));
assert.ok(route.includes("admin.qa.read") && route.includes("admin.qa.manage"));
assert.ok(dashboard.includes("qaModel.getDashboard"));
assert.ok(fs.existsSync(path.join(root, "views", "admin", "qa.ejs")));
assert.ok(fs.existsSync(path.join(root, "public", "styles", "qa.css")));
console.log("Chapter 40 testing and QA contract: PASS");
