const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const availabilityModel = require(path.join(root, "models", "availabilityModel"));
const route = fs.readFileSync(path.join(root, "routes", "availabilityRoute.js"), "utf8");
const controller = fs.readFileSync(path.join(root, "controllers", "availabilityController.js"), "utf8");
const rebuildSql = fs.readFileSync(path.join(root, "database", "rebuild.sql"), "utf8");
for (const method of ["ensureSchema", "runHealthChecks", "getDashboard", "resolveIncident", "checkService", "startMonitor"]) assert.equal(typeof availabilityModel[method], "function", `${method} should be exported`);
for (const requirement of Array.from({ length: 10 }, (_, index) => `ACC-FRS-AVAIL-${String(index + 1).padStart(3, "0")}`)) assert.ok(rebuildSql.includes(requirement), `Missing availability requirement: ${requirement}`);
for (const table of ["availability_services", "availability_health_checks", "availability_redundancy_components", "availability_incidents", "availability_failover_events", "availability_recovery_actions", "availability_audit_logs"]) assert.ok(rebuildSql.includes(table), `Missing availability table: ${table}`);
for (const routePath of ["/admin/availability", "/admin/availability/health-checks", "/admin/availability/incidents/:id/resolve"]) assert.ok(route.includes(routePath), `Missing availability route: ${routePath}`);
assert.ok(route.includes("admin.availability.read") && route.includes("admin.availability.manage"));
assert.ok(controller.includes("runHealthChecks") && controller.includes("resolveIncident"));
assert.ok(fs.existsSync(path.join(root, "views", "admin", "availability.ejs")));
assert.ok(fs.existsSync(path.join(root, "public", "styles", "availability.css")));
assert.ok(rebuildSql.includes("admin.availability.read") && rebuildSql.includes("admin.availability.manage"));
assert.ok(rebuildSql.includes("requirement_traceability") && rebuildSql.includes("chapter37-availability.test.js"));
assert.ok(rebuildSql.includes("web_application_backup"));
assert.ok(fs.readFileSync(path.join(root, "models", "availabilityModel.js"), "utf8").includes("notificationModel.generateNotification"));
console.log("Chapter 37 availability contract: PASS");
