const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const model = require(path.join(root, "models", "aiModel"));
const source = fs.readFileSync(path.join(root, "models", "aiModel.js"), "utf8");
const route = fs.readFileSync(path.join(root, "routes", "aiRoute.js"), "utf8");
const rebuild = fs.readFileSync(path.join(root, "database", "rebuild.sql"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "models", "accManagementDashboardModel.js"), "utf8");
for (const method of ["ensureSchema", "getConsent", "saveConsent", "recordInteraction", "getRecommendations", "smartSearch", "evaluateFraud", "createPrediction", "getAdminDashboard", "updateFraudCase", "updateAlert", "giveRecommendationFeedback"]) assert.equal(typeof model[method], "function", `Missing AI method: ${method}`);
for (let index = 1; index <= 10; index += 1) assert.ok(rebuild.includes(`ACC-FRS-AI-${String(index).padStart(3, "0")}`), `Missing AI requirement ${index}`);
for (const table of ["ai_user_profiles", "ai_interaction_events", "ai_recommendations", "ai_search_queries", "ai_fraud_cases", "ai_predictions", "ai_alerts", "ai_models", "ai_audit_logs"]) assert.ok(rebuild.includes(table), `Missing AI table ${table}`);
for (const routePath of ["/ai", "/ai/search", "/api/ai/search", "/api/ai/interactions", "/admin/ai", "/admin/ai/evaluate-fraud"]) assert.ok(route.includes(routePath), `Missing AI route ${routePath}`);
assert.ok(source.includes("marketplace_listings") && source.includes("orders") && source.includes("recommendations_generated") && source.includes("fraud_alert_triggered"));
assert.ok(route.includes("ai.recommendations.read") && route.includes("admin.ai.manage"));
assert.ok(dashboard.includes("aiModel.getAdminDashboard"));
assert.ok(fs.existsSync(path.join(root, "views", "ai", "dashboard.ejs")));
assert.ok(fs.existsSync(path.join(root, "views", "admin", "ai.ejs")));
assert.ok(fs.existsSync(path.join(root, "public", "styles", "ai.css")));
console.log("Chapter 43 AI and recommendation contract: PASS");
