const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const model = require(path.join(root, "models", "loggingModel"));
const source = fs.readFileSync(path.join(root, "models", "loggingModel.js"), "utf8");
const route = fs.readFileSync(path.join(root, "routes", "loggingRoute.js"), "utf8");
const controller = fs.readFileSync(path.join(root, "controllers", "loggingController.js"), "utf8");
const middleware = fs.readFileSync(path.join(root, "middleware", "errorHandler.js"), "utf8");
const rebuild = fs.readFileSync(path.join(root, "database", "rebuild.sql"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "models", "accManagementDashboardModel.js"), "utf8");
for (const method of ["ensureSchema", "recordEvent", "recordError", "getDashboard", "acknowledgeAlert"]) assert.equal(typeof model[method], "function", `${method} should be exported`);
for (const requirement of Array.from({ length: 10 }, (_, index) => `ACC-FRS-LOG-${String(index + 1).padStart(3, "0")}`)) assert.ok(rebuild.includes(requirement), `Missing logging requirement: ${requirement}`);
for (const table of ["application_logs", "error_logs", "log_retention_policies", "log_monitor_alerts"]) assert.ok(rebuild.includes(table), `Missing logging table: ${table}`);
for (const routePath of ["/admin/logging", "/admin/logging/alerts/:id"]) assert.ok(route.includes(routePath), `Missing logging route: ${routePath}`);
assert.ok(route.includes("admin.logging.read") && route.includes("admin.logging.manage"));
assert.ok(source.includes("previous_hash") && source.includes("record_hash") && source.includes("sha256"));
assert.ok(source.includes("retention_days") && source.includes("error_anomaly"));
assert.ok(middleware.includes("loggingModel.recordError"));
assert.ok(middleware.includes("route_not_found"));
assert.ok(middleware.includes("Service temporarily unavailable"));
assert.ok(rebuild.includes("requirement_traceability") && rebuild.includes("chapter39-logging.test.js"));
assert.ok(rebuild.indexOf("CREATE TABLE permissions") < rebuild.indexOf("admin.logging.read"), "Logging permissions must be seeded after RBAC tables.");
assert.ok(rebuild.indexOf("CREATE TABLE role_permissions") < rebuild.indexOf("admin.logging.read"), "Logging role permissions must be seeded after RBAC tables.");
assert.ok(fs.existsSync(path.join(root, "views", "admin", "logging.ejs")));
assert.ok(fs.existsSync(path.join(root, "public", "styles", "logging.css")));
assert.ok(controller.includes("getDashboard") && controller.includes("acknowledgeAlert"));
assert.ok(dashboard.includes("loggingModel.getDashboard"));
console.log("Chapter 39 logging and error handling contract: PASS");
