const express = require("express");
const { ensureAuthenticated, ensureVerifiedAccount } = require("../controllers/accountController");
const { requirePermission, requireRole } = require("../middleware/rbacMiddleware");
const controller = require("../controllers/aiController");
const router = express.Router();
const memberAccess = [ensureAuthenticated, ensureVerifiedAccount, requirePermission("ai.recommendations.read")];
const adminAccess = [ensureAuthenticated, requireRole("platform_admin", "system_admin", "acc_management_admin", "super_admin", "compliance_officer")];
router.get("/ai", ...memberAccess, controller.dashboard);
router.get("/ai/search", ...memberAccess, controller.searchPage);
router.get("/api/ai/search", ...memberAccess, controller.search);
router.post("/api/ai/interactions", ...memberAccess, requirePermission("ai.interactions.write"), controller.interaction);
router.post("/api/ai/recommendations/:id/feedback", ...memberAccess, requirePermission("ai.interactions.write"), controller.feedback);
router.post("/ai/privacy", ...memberAccess, requirePermission("ai.interactions.write"), controller.consent);
router.post("/ai/predictions", ...memberAccess, controller.prediction);
router.get("/admin/ai", ...adminAccess, requirePermission("admin.ai.read"), controller.adminPage);
router.post("/admin/ai/fraud/:id", ...adminAccess, requirePermission("admin.ai.manage"), controller.fraudStatus);
router.post("/admin/ai/alerts/:id", ...adminAccess, requirePermission("admin.ai.manage"), controller.alertStatus);
router.post("/admin/ai/evaluate-fraud", ...adminAccess, requirePermission("admin.ai.manage"), controller.evaluateFraud);
module.exports = router;
