/*
 * contractDocumentStorage.js - Private contract document storage adapter.
 * Files are kept outside public/ so access is controlled by contract routes.
 */
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const multer = require("multer");
const PDFDocument = require("pdfkit");

// Store legal documents privately and create the directory during application startup.
const contractStorageDirectory = path.join(__dirname, "..", "storage", "contracts");
fs.mkdirSync(contractStorageDirectory, { recursive: true });

// Generate collision-resistant names without preserving user-controlled path segments.
const storage = multer.diskStorage({
  destination: (req, file, callback) => callback(null, contractStorageDirectory),
  filename: (req, file, callback) => callback(null, `${Date.now()}-${crypto.randomBytes(12).toString("hex")}${path.extname(file.originalname).toLowerCase()}`),
});

// Accept only common contract and supporting-document formats.
function contractDocumentFilter(req, file, callback) {
  const allowedExtensions = [".pdf", ".doc", ".docx", ".png", ".jpg", ".jpeg"];
  const extension = path.extname(file.originalname).toLowerCase();
  if (!allowedExtensions.includes(extension)) return callback(new Error("Only PDF, DOC, DOCX, JPG, JPEG, and PNG documents are supported."));
  return callback(null, true);
}

// Limit document size to 10 MB while leaving larger files rejected by Multer.
const contractDocumentUpload = multer({ storage, fileFilter: contractDocumentFilter, limits: { fileSize: 10 * 1024 * 1024 } });

// Resolve only filenames generated by this adapter.
function getPrivateDocumentPath(storageName) {
  const safeName = path.basename(String(storageName || ""));
  if (!safeName || safeName !== String(storageName || "")) return null;
  return path.join(contractStorageDirectory, safeName);
}

// Remove an uploaded file when a later contract operation fails.
function removePrivateDocument(storageName) {
  const filePath = getPrivateDocumentPath(storageName);
  if (filePath && fs.existsSync(filePath)) fs.unlinkSync(filePath);
}

// Generate the main contract PDF in private storage so template output is a real document.
function generateContractPdf(contract) {
  return new Promise((resolve, reject) => {
    const storageName = `${Date.now()}-${crypto.randomBytes(12).toString("hex")}.pdf`;
    const filePath = getPrivateDocumentPath(storageName);
    const document = new PDFDocument({ margin: 54 });
    const stream = fs.createWriteStream(filePath);
    stream.on("finish", () => resolve({ storageName, fileName: `${contract.reference}.pdf` }));
    stream.on("error", reject);
    document.pipe(stream);
    document.fontSize(18).text(contract.title, { align: "center" });
    document.moveDown();
    document.fontSize(10).text(`Contract reference: ${contract.reference}`);
    document.text(`Version: ${contract.version}`);
    document.text(`Effective date: ${contract.effectiveDate}`);
    document.text(`Expiration date: ${contract.expirationDate}`);
    document.moveDown();
    document.fontSize(11).text(contract.content || contract.description, { lineGap: 4 });
    document.end();
  });
}

// Export the upload middleware and guarded storage helpers.
module.exports = { contractDocumentUpload, getPrivateDocumentPath, removePrivateDocument, generateContractPdf, contractStorageDirectory };
