/*
 * disputeModel.js - ACC Chapter 24 dispute resolution lifecycle.
 * The service adds structured trust protection around existing orders and contracts.
 */
const crypto = require("crypto");
const orderModel = require("./orderModel");
const paymentModel = require("./paymentModel");
const contractModel = require("./contractModel");
const pool = require("../database/connection");

const disputeStatuses = ["open", "under_review", "in_mediation", "resolved", "escalated", "closed"];
const resolutionTypes = ["refund", "replacement", "partial_compensation", "no_action"];
const evidenceTypes = ["document", "image", "communication_log", "transaction_history"];
function generateReference(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; }
function isModerator(user) { return Boolean(user && ["admin", "moderator", "platform_admin", "dispute_officer"].includes(String(user.role || "").toLowerCase())); }
function normalizeDispute(dispute) { return { ...dispute, id: Number(dispute.id), partyIds: [...dispute.partyIds].map(Number), orderId: dispute.orderId ? Number(dispute.orderId) : null, contractId: dispute.contractId ? Number(dispute.contractId) : null, moderatorId: dispute.moderatorId ? Number(dispute.moderatorId) : null }; }
async function resolveReference(payload) {
	const orderId = Number(payload.orderId || 0) || null;
	const contractId = Number(payload.contractId || 0) || null;
	if (!orderId && !contractId) return { success: false, message: "Link the dispute to an order or contract." };
	if (orderId) {
		const order = await orderModel.getOrderById(orderId);
		if (!order) return { success: false, message: "The linked order was not found." };
		return { success: true, orderId, partyIds: [Number(order.buyerId), Number(order.sellerId)], paymentId: null };
	}
	const contract = await contractModel.getContractById(contractId, Number(payload.creatorId));
	if (!contract) return { success: false, message: "The linked contract was not found or is not accessible." };
	return { success: true, contractId, partyIds: contract.partyIds, paymentId: contract.paymentId || null };
}

const disputeColumns = `id, dispute_reference AS reference, order_id AS "orderId", contract_id AS "contractId", payment_id AS "paymentId", raised_by AS "raisedBy", issue_description AS "issueDescription", status, moderator_id AS "moderatorId", resolution_type AS "resolutionType", resolution_details AS "resolutionDetails", created_at AS "createdAt", updated_at AS "updatedAt", resolved_at AS "resolvedAt", closed_at AS "closedAt"`;
async function disputeParties(record) { if (record.orderId) { const order = await orderModel.getOrderById(record.orderId); return order ? [order.buyerId, order.sellerId] : []; } if (record.contractId) { const contract = await contractModel.getContractById(record.contractId, record.raisedBy); return contract && contract.partyIds ? contract.partyIds.map(Number) : []; } return []; }
async function disputeRecord(id) { const result = await pool.query(`SELECT ${disputeColumns} FROM disputes WHERE id=$1`, [id]); if (!result.rows[0]) return null; const record = result.rows[0]; record.partyIds = await disputeParties(record); return normalizeDispute(record); }
async function disputeAudit(client, disputeId, userId, eventType, details = {}) { const result = await client.query("INSERT INTO dispute_audit_logs (dispute_id,user_id,event_type,outcome,details) VALUES ($1,$2,$3,'success',$4) RETURNING id,event_type AS \"eventType\",outcome,details,created_at AS \"createdAt\"", [disputeId, userId || null, eventType, details]); return result.rows[0]; }
async function createDispute(creatorId, payload = {}) { const issue = String(payload.issueDescription || payload.reason || "").trim(); if (!creatorId || !issue) return { success: false, message: "A clear dispute description is required." }; const reference = await resolveReference({ ...payload, creatorId }); if (!reference.success) return reference; if (!reference.partyIds.includes(Number(creatorId))) return { success: false, message: "Only a linked transaction party can raise this dispute." }; const client = await pool.connect(); try { await client.query("BEGIN"); const result = await client.query(`INSERT INTO disputes (dispute_reference,order_id,contract_id,payment_id,raised_by,issue_description) VALUES ($1,$2,$3,$4,$5,$6) RETURNING ${disputeColumns}`, [generateReference("DSP"), reference.orderId || null, reference.contractId || null, Number(payload.paymentId || reference.paymentId || 0) || null, creatorId, issue]); const record = result.rows[0]; record.partyIds = reference.partyIds; await disputeAudit(client, record.id, creatorId, "dispute_created", { disputeId: record.id, orderId: record.orderId, contractId: record.contractId }); await client.query("COMMIT"); return { success: true, dispute: normalizeDispute(record), message: "Dispute created and the opposing party was notified." }; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function getDisputesForUser(userId, user = null) { const result = await pool.query(`SELECT ${disputeColumns} FROM disputes ${isModerator(user) ? "" : "WHERE raised_by=$1 OR order_id IN (SELECT id FROM orders WHERE buyer_id=$1 OR seller_id=$1)"} ORDER BY updated_at DESC`, isModerator(user) ? [] : [userId]); const records = []; for (const row of result.rows) { row.partyIds = await disputeParties(row); if (isModerator(user) || row.partyIds.includes(Number(userId))) records.push(normalizeDispute(row)); } return records; }
async function getDisputeById(disputeId, userId, user = null) { const record = await disputeRecord(disputeId); return record && (isModerator(user) || record.partyIds.includes(Number(userId))) ? record : null; }
async function changeDispute(user, disputeId, values, eventType, message, predicate = () => true) { if (!isModerator(user)) return { success: false, message: "Moderator access is required." }; const client = await pool.connect(); try { await client.query("BEGIN"); const found = await client.query(`SELECT ${disputeColumns} FROM disputes WHERE id=$1 FOR UPDATE`, [disputeId]); if (!found.rows[0]) { await client.query("ROLLBACK"); return { success: false, message: "Moderator access is required." }; } if (!predicate(found.rows[0])) { await client.query("ROLLBACK"); return { success: false, message: "This dispute cannot be updated in its current state." }; } const set = Object.keys(values).map((key, i) => `${key}=$${i + 2}`).join(","); const result = await client.query(`UPDATE disputes SET ${set},updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING ${disputeColumns}`, [disputeId, ...Object.values(values)]); await disputeAudit(client, disputeId, user.id, eventType, { disputeId, status: result.rows[0].status }); await client.query("COMMIT"); const record = result.rows[0]; record.partyIds = await disputeParties(record); return { success: true, dispute: normalizeDispute(record), message }; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function assignModerator(user, disputeId, moderatorId) { return changeDispute(user, disputeId, { moderator_id: Number(moderatorId || user.id), status: "under_review" }, "status_changed", "Dispute assigned for review."); }
async function initiateMediation(user, disputeId) { return changeDispute(user, disputeId, { status: "in_mediation" }, "status_changed", "Dispute moved into mediation."); }
async function escalateDispute(user, disputeId, reason = "") { return changeDispute(user, disputeId, { status: "escalated" }, "status_changed", "Dispute escalated for higher review.", (record) => !["resolved", "closed"].includes(record.status)); }
async function closeDispute(user, disputeId) { return changeDispute(user, disputeId, { status: "closed", closed_at: new Date() }, "status_changed", "Dispute closed successfully.", (record) => record.status === "resolved"); }
async function submitEvidence(userId, disputeId, payload = {}) { const dispute = await disputeRecord(disputeId); const type = String(payload.evidenceType || "document").toLowerCase(); if (!dispute || !dispute.partyIds.includes(Number(userId))) return { success: false, message: "Only a dispute party can submit evidence." }; if (!["open", "under_review", "in_mediation", "escalated"].includes(dispute.status)) return { success: false, message: "Evidence cannot be added after resolution." }; if (!evidenceTypes.includes(type) || (!payload.fileName && !payload.content)) return { success: false, message: "Provide supported evidence content." }; const client = await pool.connect(); try { await client.query("BEGIN"); const checksum = crypto.createHash("sha256").update(String(payload.storageName || payload.content || payload.fileName)).digest("hex"); const result = await client.query("INSERT INTO dispute_evidence (dispute_id,submitted_by,evidence_type,file_name,storage_name,checksum,content) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id,dispute_id AS \"disputeId\",submitted_by AS \"submittedBy\",evidence_type AS \"evidenceType\",file_name AS \"fileName\",checksum,content,created_at AS \"createdAt\"", [disputeId, userId, type, String(payload.fileName || ""), String(payload.storageName || ""), checksum, String(payload.content || "")]); await client.query("UPDATE disputes SET updated_at=CURRENT_TIMESTAMP WHERE id=$1", [disputeId]); await disputeAudit(client, disputeId, userId, "evidence_submitted", { disputeId, evidenceId: result.rows[0].id, evidenceType: type }); await client.query("COMMIT"); return { success: true, evidence: result.rows[0], message: "Evidence submitted securely." }; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function resolveDispute(user, disputeId, resolutionType, details = "") { const type = String(resolutionType || "").toLowerCase(); if (!resolutionTypes.includes(type)) return { success: false, message: "Select a supported resolution type." }; const dispute = await disputeRecord(disputeId); if (!dispute || !isModerator(user)) return { success: false, message: "Moderator access is required." }; const result = await changeDispute(user, disputeId, { resolution_type: type, resolution_details: String(details || ""), status: "resolved", resolved_at: new Date() }, "resolution_executed", "Dispute resolution recorded."); let refund = null; if (result.success && type === "refund" && result.dispute.paymentId) refund = await paymentModel.refundPayment(result.dispute.raisedBy, result.dispute.paymentId, `Dispute ${result.dispute.reference} resolved by refund.`); return { ...result, refund }; }
async function getEvidence(disputeId, userId, user = null) { const dispute = await disputeRecord(disputeId); if (!dispute || (!isModerator(user) && !dispute.partyIds.includes(Number(userId)))) return []; const result = await pool.query("SELECT id,dispute_id AS \"disputeId\",submitted_by AS \"submittedBy\",evidence_type AS \"evidenceType\",file_name AS \"fileName\",checksum,content,created_at AS \"createdAt\" FROM dispute_evidence WHERE dispute_id=$1 ORDER BY created_at,id", [disputeId]); return result.rows; }
async function getAuditLog() { const result = await pool.query("SELECT id,dispute_id AS \"disputeId\",user_id AS \"userId\",event_type AS \"eventType\",outcome,details,created_at AS \"createdAt\" FROM dispute_audit_logs ORDER BY created_at,id"); return result.rows; }
async function getNotificationLog() { return []; }

module.exports = { disputeStatuses, resolutionTypes, evidenceTypes, isModerator, createDispute, getDisputesForUser, getDisputeById, assignModerator, submitEvidence, initiateMediation, resolveDispute, escalateDispute, closeDispute, getEvidence, getAuditLog, getNotificationLog };
