/* PostgreSQL-authoritative procurement workflow for ACC Chapter 22. */
const pool = require("../database/connection");
const notificationModel = require("./notificationModel");
const procurementVisibilities = ["open", "restricted"];
const procurementStatuses = ["draft", "open", "closed", "under_evaluation", "awarded", "cancelled"];
const quotationStatuses = ["pending", "accepted", "rejected"];
const rfqColumns = `r.id, r.rfq_reference AS "reference", r.buyer_id AS "buyerId", r.title, r.description, r.category, r.quantity_required AS "quantityRequired", r.unit_of_measurement AS "unitOfMeasurement", r.budget_amount AS "budgetAmount", r.budget_currency AS "budgetCurrency", r.delivery_location AS "deliveryLocation", r.delivery_date_required AS "deadline", r.visibility, r.status, r.created_at AS "createdAt", r.updated_at AS "updatedAt"`;
const quotationColumns = `q.id, q.quote_reference AS "reference", q.rfq_id AS "rfqId", q.supplier_id AS "supplierId", q.quoted_price AS "quotedPrice", q.currency, q.delivery_timeframe AS "deliveryTimeframe", q.terms_conditions AS "termsConditions", q.status, q.created_at AS "createdAt", q.updated_at AS "updatedAt"`;
const orderColumns = `o.id, o.procurement_reference AS "reference", o.quotation_id AS "quotationId", o.buyer_id AS "buyerId", o.supplier_id AS "supplierId", o.order_amount AS "orderAmount", o.currency, o.payment_status AS "paymentStatus", o.delivery_status AS "deliveryStatus", o.status, o.created_at AS "createdAt", o.created_at AS "updatedAt"`;
const number = (value) => Number(value || 0);
function normalizeRFQ(row) { return { ...row, id: number(row.id), buyerId: number(row.buyerId), quantityRequired: number(row.quantityRequired), budgetAmount: row.budgetAmount === null ? null : Number(row.budgetAmount), supplierIds: (row.supplierIds || []).map(Number) }; }
function normalizeQuotation(row) { return { ...row, id: number(row.id), rfqId: number(row.rfqId), supplierId: number(row.supplierId), quotedPrice: Number(row.quotedPrice) }; }
function normalizeOrder(row) { const order = { ...row, id: number(row.id), buyerId: number(row.buyerId), supplierId: number(row.supplierId), quotationId: number(row.quotationId), rfqId: number(row.rfqId), orderAmount: Number(row.orderAmount) }; return { ...order, paymentPath: `/payments?procurementOrderId=${order.id}`, logisticsPath: `/logistics?procurementOrderId=${order.id}`, contractPath: `/contracts/create?procurementOrderId=${order.id}` }; }
async function rfqById(client, id) { const result = await client.query(`SELECT ${rfqColumns}, COALESCE(array_agg(s.supplier_id) FILTER (WHERE s.supplier_id IS NOT NULL), '{}') AS "supplierIds" FROM procurement_rfqs r LEFT JOIN procurement_rfq_suppliers s ON s.rfq_id=r.id WHERE r.id=$1 GROUP BY r.id`, [id]); return result.rows[0] ? normalizeRFQ(result.rows[0]) : null; }
async function audit(client, eventType, details, userId) { const result = await client.query(`INSERT INTO procurement_audit_logs (rfq_id,quotation_id,order_id,user_id,event_type,outcome,details) VALUES ($1,$2,$3,$4,$5,'success',$6) RETURNING id,event_type AS "eventType",outcome,details,created_at AS "createdAt"`, [details.rfqId || null, details.quotationId || null, details.procurementOrderId || null, userId || null, eventType, details]); return result.rows[0]; }
function notify(type, payload) { notificationModel.generateFromEvent(type, payload); }
function supplierIds(value) { return String(value || "").split(",").map((item) => Number(item.trim())).filter(Boolean); }
async function createRFQ(buyerId, payload = {}) { const title = String(payload.title || "").trim(), description = String(payload.description || "").trim(), category = String(payload.category || "").trim(), quantityRequired = Number(payload.quantityRequired || 0), deadline = String(payload.deadline || "").trim(), visibility = String(payload.visibility || "open").trim().toLowerCase(), budgetAmount = payload.budgetAmount === "" || payload.budgetAmount === undefined ? null : Number(payload.budgetAmount); if (!buyerId || !title || !description || !category || quantityRequired <= 0 || !deadline) return { success: false, message: "Title, description, category, quantity, and deadline are required." }; if (!procurementVisibilities.includes(visibility)) return { success: false, message: "Select an open or restricted procurement type." }; if (Number.isNaN(budgetAmount) || (budgetAmount !== null && budgetAmount < 0)) return { success: false, message: "Budget must be a valid positive amount or left blank." }; if (Number.isNaN(new Date(deadline).getTime())) return { success: false, message: "Enter a valid procurement deadline." }; const client = await pool.connect(); try { await client.query("BEGIN"); const result = await client.query(`INSERT INTO procurement_rfqs (rfq_reference,buyer_id,title,description,category,quantity_required,unit_of_measurement,budget_amount,budget_currency,delivery_location,delivery_date_required,visibility,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'draft') RETURNING id`, [`RFQ-${Date.now()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`, buyerId, title, description, category, quantityRequired, String(payload.unitOfMeasurement || "units").trim(), budgetAmount, String(payload.budgetCurrency || "USD").trim().toUpperCase(), String(payload.deliveryLocation || "").trim() || null, deadline, visibility]); const id = result.rows[0].id; for (const supplierId of supplierIds(payload.supplierIds)) await client.query("INSERT INTO procurement_rfq_suppliers (rfq_id,supplier_id) VALUES ($1,$2) ON CONFLICT DO NOTHING", [id, supplierId]); await audit(client, "request_created", { rfqId: id }, buyerId); const rfq = await rfqById(client, id); await client.query("COMMIT"); return { success: true, rfq, message: "Procurement request created as a draft." }; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function publishRFQ(buyerId, rfqId) { const client = await pool.connect(); try { await client.query("BEGIN"); const rfq = await rfqById(client, rfqId); if (!rfq) { await client.query("ROLLBACK"); return { success: false, message: "Procurement request not found." }; } if (rfq.buyerId !== number(buyerId)) { await client.query("ROLLBACK"); return { success: false, message: "Only the buyer can publish this request." }; } if (rfq.status !== "draft") { await client.query("ROLLBACK"); return { success: false, message: "Only draft requests can be published." }; } await client.query("UPDATE procurement_rfqs SET status='open',updated_at=CURRENT_TIMESTAMP WHERE id=$1", [rfqId]); await audit(client, "request_published", { rfqId }, buyerId); const updated = await rfqById(client, rfqId); await client.query("COMMIT"); notify("new_request_published", { rfqId: updated.id, buyerId: updated.buyerId, title: updated.title }); return { success: true, rfq: updated, message: "Procurement request published successfully." }; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function getAvailableRFQs(supplierId) { const result = await pool.query(`SELECT ${rfqColumns}, COALESCE(array_agg(s.supplier_id) FILTER (WHERE s.supplier_id IS NOT NULL), '{}') AS "supplierIds" FROM procurement_rfqs r LEFT JOIN procurement_rfq_suppliers s ON s.rfq_id=r.id WHERE r.status IN ('open','under_evaluation') AND (r.visibility='open' OR EXISTS (SELECT 1 FROM procurement_rfq_suppliers x WHERE x.rfq_id=r.id AND x.supplier_id=$1)) GROUP BY r.id ORDER BY r.created_at DESC`, [supplierId]); return result.rows.map(normalizeRFQ); }
async function getBuyerRFQs(buyerId) { const result = await pool.query(`SELECT ${rfqColumns}, COALESCE(array_agg(s.supplier_id) FILTER (WHERE s.supplier_id IS NOT NULL), '{}') AS "supplierIds" FROM procurement_rfqs r LEFT JOIN procurement_rfq_suppliers s ON s.rfq_id=r.id WHERE r.buyer_id=$1 GROUP BY r.id ORDER BY r.created_at DESC`, [buyerId]); return result.rows.map(normalizeRFQ); }
async function getRFQById(rfqId, viewerId) { const rfq = await rfqById(pool, rfqId); return rfq && (rfq.buyerId === number(viewerId) || (["open", "under_evaluation"].includes(rfq.status) && (rfq.visibility === "open" || rfq.supplierIds.includes(number(viewerId))))) ? rfq : null; }
async function submitQuotation(supplierId, rfqId, payload = {}) { const client = await pool.connect(); try { await client.query("BEGIN"); const rfq = await rfqById(client, rfqId), quotedPrice = Number(payload.quotedPrice || 0); if (!rfq) { await client.query("ROLLBACK"); return { success: false, message: "Procurement request not found." }; } if (rfq.buyerId === number(supplierId)) { await client.query("ROLLBACK"); return { success: false, message: "A buyer cannot bid on its own request." }; } if (!["open", "under_evaluation"].includes(rfq.status)) { await client.query("ROLLBACK"); return { success: false, message: "This procurement request is not accepting bids." }; } if (new Date(rfq.deadline).getTime() < Date.now()) { await client.query("ROLLBACK"); return { success: false, message: "The bid deadline has passed." }; } if (rfq.visibility === "restricted" && !rfq.supplierIds.includes(number(supplierId))) { await client.query("ROLLBACK"); return { success: false, message: "This request is restricted to invited suppliers." }; } if (quotedPrice <= 0) { await client.query("ROLLBACK"); return { success: false, message: "Enter a valid quotation amount." }; } const duplicate = await client.query("SELECT 1 FROM procurement_quotations WHERE rfq_id=$1 AND supplier_id=$2", [rfqId, supplierId]); if (duplicate.rows.length) { await client.query("ROLLBACK"); return { success: false, message: "You have already submitted a quotation for this request." }; } const result = await client.query(`INSERT INTO procurement_quotations (rfq_id,supplier_id,quote_reference,quoted_price,currency,delivery_timeframe,terms_conditions,status) VALUES ($1,$2,$3,$4,$5,$6,$7,'pending') RETURNING ${quotationColumns}`, [rfqId, supplierId, `QTE-${Date.now()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`, quotedPrice, String(payload.currency || rfq.budgetCurrency).trim().toUpperCase(), String(payload.deliveryTimeframe || "").trim(), String(payload.termsConditions || "").trim()]); await client.query("UPDATE procurement_rfqs SET status='under_evaluation',updated_at=CURRENT_TIMESTAMP WHERE id=$1", [rfqId]); const quotation = normalizeQuotation(result.rows[0]); await audit(client, "bid_submitted", { rfqId: number(rfqId), quotationId: quotation.id }, supplierId); await client.query("COMMIT"); notify("bid_submitted", { rfqId, quotationId: quotation.id, buyerId: rfq.buyerId, supplierId }); return { success: true, quotation, message: "Quotation submitted successfully." }; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function getQuotationsForRFQ(rfqId, viewerId) { const rfq = await rfqById(pool, rfqId); if (!rfq || rfq.buyerId !== number(viewerId)) return []; const result = await pool.query(`SELECT ${quotationColumns} FROM procurement_quotations q WHERE q.rfq_id=$1 ORDER BY q.created_at`, [rfqId]); return result.rows.map(normalizeQuotation); }
async function getSupplierQuotations(supplierId) { const result = await pool.query(`SELECT ${quotationColumns} FROM procurement_quotations q WHERE q.supplier_id=$1 ORDER BY q.created_at DESC`, [supplierId]); return result.rows.map(normalizeQuotation); }
async function awardQuotation(buyerId, rfqId, quotationId) { const client = await pool.connect(); try { await client.query("BEGIN"); const rfq = await rfqById(client, rfqId), result = await client.query(`SELECT ${quotationColumns} FROM procurement_quotations q WHERE q.id=$1 AND q.rfq_id=$2 FOR UPDATE`, [quotationId, rfqId]); if (!rfq || !result.rows[0]) { await client.query("ROLLBACK"); return { success: false, message: "Request or quotation not found." }; } if (rfq.buyerId !== number(buyerId)) { await client.query("ROLLBACK"); return { success: false, message: "Only the buyer can award this request." }; } if (!["open", "under_evaluation"].includes(rfq.status)) { await client.query("ROLLBACK"); return { success: false, message: "This request is no longer available for award." }; } const quotation = normalizeQuotation(result.rows[0]); await client.query("UPDATE procurement_quotations SET status='accepted',updated_at=CURRENT_TIMESTAMP WHERE id=$1", [quotationId]); await client.query("UPDATE procurement_quotations SET status='rejected',updated_at=CURRENT_TIMESTAMP WHERE rfq_id=$1 AND id<>$2", [rfqId, quotationId]); const order = await client.query(`INSERT INTO procurement_orders (procurement_reference,buyer_id,supplier_id,quotation_id,order_amount,currency,status) VALUES ($1,$2,$3,$4,$5,$6,'confirmed') RETURNING ${orderColumns}`, [`PO-${Date.now()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`, rfq.buyerId, quotation.supplierId, quotation.id, quotation.quotedPrice, quotation.currency]); const normalized = normalizeOrder({ ...order.rows[0], rfqId: number(rfqId) }); await client.query("UPDATE procurement_rfqs SET status='awarded',updated_at=CURRENT_TIMESTAMP WHERE id=$1", [rfqId]); await audit(client, "award_made", { rfqId: number(rfqId), quotationId: quotation.id, procurementOrderId: normalized.id }, buyerId); await client.query("COMMIT"); notify("bid_accepted", { rfqId, quotationId: quotation.id, procurementOrderId: normalized.id, supplierId: quotation.supplierId }); return { success: true, order: normalized, message: "Procurement awarded and fulfillment hand-off created." }; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function closeRFQ(buyerId, rfqId) { const result = await pool.query(`UPDATE procurement_rfqs SET status='closed',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND buyer_id=$2 AND status IN ('open','under_evaluation') RETURNING ${rfqColumns}`, [rfqId, buyerId]); if (!result.rows[0]) return { success: false, message: "This request cannot be closed in its current state." }; await pool.query("INSERT INTO procurement_audit_logs (rfq_id,user_id,event_type,outcome,details) VALUES ($1,$2,'request_closed','success',$3)", [rfqId, buyerId, { rfqId: number(rfqId) }]); return { success: true, rfq: normalizeRFQ(result.rows[0]), message: "Procurement request closed successfully." }; }
async function getAuditLog() { const result = await pool.query(`SELECT id,rfq_id AS "rfqId",quotation_id AS "quotationId",order_id AS "procurementOrderId",user_id AS "userId",event_type AS "eventType",outcome,details,created_at AS "createdAt" FROM procurement_audit_logs ORDER BY created_at,id`); return result.rows; }
async function getNotificationLog() { return []; }
async function getProcurementOrdersForUser(userId) { const result = await pool.query(`SELECT ${orderColumns}, q.rfq_id AS "rfqId" FROM procurement_orders o LEFT JOIN procurement_quotations q ON q.id=o.quotation_id WHERE o.buyer_id=$1 OR o.supplier_id=$1 ORDER BY o.created_at DESC`, [userId]); return result.rows.map(normalizeOrder); }
module.exports = { procurementVisibilities, procurementStatuses, quotationStatuses, createRFQ, publishRFQ, getAvailableRFQs, getBuyerRFQs, getRFQById, submitQuotation, getQuotationsForRFQ, getSupplierQuotations, awardQuotation, closeRFQ, getAuditLog, getNotificationLog, getProcurementOrdersForUser };
